version: "3.8"
name: "${APP_NAME}-brace"

x-debug: &xdebug
  XDEBUG_CONFIG: >-
    client_host=host.docker.internal
  PHP_XDEBUG_ENABLED: 1
  XDEBUG_MODE: develop,debug,coverage

services:
  web:
    container_name: "${APP_NAME}-web"
    build:
      context: ./docker
      dockerfile: "Dockerfile"
    image: "brace-app"
    ports:
      - "80:80"
    environment:
      <<: *xdebug
    networks:
      - brace
    volumes:
      - ".:/var/www/html"
    depends_on:
      - mariadb

  mariadb:
    container_name: "${APP_NAME}-db"
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "brace-data:/var/lib/mysql"
      - "./docker/scripts/create-testing-db.sh:/docker-entrypoint-initdb.d/create-testing-db.sh"
    networks:
      - brace

networks:
  brace:
    driver: bridge

volumes:
  brace-data:
    driver: local