version: "3.8"
name: brace-app

services:
  web:
    container_name: "web"
    build:
      context: ./docker
      dockerfile: "Dockerfile"
    image: "brace-app"
    ports:
      - "80:80"
    environment:
      XDEBUG_MODE: "develop,debug,coverage"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    networks:
      - brace
    volumes:
      - ".:/var/www/html"
    depends_on:
      - mariadb

  mariadb:
    container_name: "db"
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "brace-data:/var/lib/mysql"
    networks:
      - brace

networks:
  brace:
    driver: bridge

volumes:
  brace-data:
    driver: local