version: "3.8"
name: "${APP_NAME}"

x-debug: &xdebug
  XDEBUG_CONFIG: client_host=host.docker.internal
  PHP_XDEBUG_ENABLED: 1
  XDEBUG_MODE: develop,debug,coverage

services:
  web:
    container_name: "${APP_NAME}-web"
    build:
      context: ./docker
      dockerfile: "Dockerfile"
    image: "brace-php-simple"
    ports:
      - "80:80"
      - "5173:5173"
    environment:
      <<: *xdebug
    networks:
      - brace
    volumes:
      - ".:/var/www"
    depends_on:
      - mariadb

  mariadb:
    container_name: "${APP_NAME}-db"
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "brace-data:/var/lib/mysql"
    networks:
      - brace

networks:
  brace:
    driver: bridge

volumes:
  brace-data:
    driver: local